using RoR2;
using RoR2.Networking;

using UnityEngine;
using WolfoQoL_Client.Reminders;

namespace WolfoQoL_Client.Text
{
    public static class TextMain
    {
        public static void Start()
        {
            if (WConfig.module_text_reminders.Value)
            {
                Reminders_Main.Start();
            }
            if (WConfig.module_text_chat.Value)
            {
                MoreMessages.Start();
            }
            if (WConfig.module_text_general.Value)
            {
                LunarSeer.Start();
                EquipmentDrone.Start();
                OptionsInChat.Start();
                ShrineShapingMessage.Start();
                TextChanges.Main();
            }

            //On.RoR2.SubjectChatMessage.GetSubjectName += IncludeEliteTypeInSubjectName;
            //On.RoR2.Util.GetBestBodyName += MarriedLemurianNameHook; //Maybe a little excessive idk
            ItemCatalog.availability.CallWhenAvailable(TextChanges.UntieredItemTokens);
            GameModeCatalog.availability.CallWhenAvailable(CallLate);
        }

        public static void CallLate()
        {
            Debug.Log(NetworkMessageHandlerAttribute.clientMessageHandlers.Count);
            Debug.Log(NetworkMessageHandlerAttribute.serverMessageHandlers.Count);

            foreach (var handler in NetworkMessageHandlerAttribute.clientMessageHandlers)
            {
                Debug.Log(handler.target);
            }

            MoreMessages.VanillaVoids_WatchBrokeItem = ItemCatalog.FindItemIndex("VV_ITEM_BROKEN_MESS");
            PrayerBeads.moffeine = ItemCatalog.FindItemIndex("MoffeinBeadStatItem");
            PrayerBeads.usedBeads = ItemCatalog.FindItemIndex("ExtraStatsOnLevelUpConsumed");
            TextMain.LemurianBruiser = BodyCatalog.FindBodyIndex("LemurianBruiserBody");
            if (WConfig.module_text_general.Value)
            {
                PrayerBeads.Start();
                TextChanges.AutoGeneratedText();
               

            }


        }

        private static string IncludeEliteTypeInSubjectName(On.RoR2.SubjectChatMessage.orig_GetSubjectName orig, SubjectChatMessage self)
        {
            if (self.subjectAsNetworkUser == null && self.subjectAsCharacterBody)
            {
                return RoR2.Util.GetBestBodyName(self.subjectAsCharacterBody.gameObject);
            }
            return orig(self);
        }

        public static BodyIndex LemurianBruiser = BodyIndex.None;
        public static string MarriedLemurianNameHook(On.RoR2.Util.orig_GetBestBodyName orig, GameObject bodyObject)
        {
            if (bodyObject)
            {
                CharacterBody characterBody = bodyObject.GetComponent<CharacterBody>();
                if (characterBody && characterBody.bodyIndex == LemurianBruiser)
                {
                    if (characterBody.inventory.GetItemCount(RoR2Content.Items.Clover) >= 20)
                    {
                        if (characterBody.inventory.GetItemCount(RoR2Content.Items.FireRing) > 0)
                        {
                            return "Kjaro";
                        }
                        else if (characterBody.inventory.GetItemCount(RoR2Content.Items.IceRing) > 0)
                        {
                            return "Runald";
                        }
                    }
                }
            }
            return orig(bodyObject);
        }




    }

}
