//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfoQualityOfLife.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WolfoQualityOfLife.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AffixLostTranistBlighted {
            get {
                object obj = ResourceManager.GetObject("AffixLostTranistBlighted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AffixLostTransitFrenzied {
            get {
                object obj = ResourceManager.GetObject("AffixLostTransitFrenzied", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AffixLostTransitLeech {
            get {
                object obj = ResourceManager.GetObject("AffixLostTransitLeech", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AffixLostTransitVolatile {
            get {
                object obj = ResourceManager.GetObject("AffixLostTransitVolatile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AffixRoR2Echo {
            get {
                object obj = ResourceManager.GetObject("AffixRoR2Echo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AffixRoR2Lunar {
            get {
                object obj = ResourceManager.GetObject("AffixRoR2Lunar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] autogen_AncientWispBody {
            get {
                object obj = ResourceManager.GetObject("autogen_AncientWispBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] autogen_ArchWispBody {
            get {
                object obj = ResourceManager.GetObject("autogen_ArchWispBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] autogen_HANDBody {
            get {
                object obj = ResourceManager.GetObject("autogen_HANDBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] autogen_texBodyOldBanditIcon {
            get {
                object obj = ResourceManager.GetObject("autogen_texBodyOldBanditIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] betaCorpse {
            get {
                object obj = ResourceManager.GetObject("betaCorpse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] betaEffigy {
            get {
                object obj = ResourceManager.GetObject("betaEffigy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] betaHelfire {
            get {
                object obj = ResourceManager.GetObject("betaHelfire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] betaPauldron {
            get {
                object obj = ResourceManager.GetObject("betaPauldron", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] betaTempest {
            get {
                object obj = ResourceManager.GetObject("betaTempest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] betaWicked {
            get {
                object obj = ResourceManager.GetObject("betaWicked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CauldronIcon {
            get {
                object obj = ResourceManager.GetObject("CauldronIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CellIcon {
            get {
                object obj = ResourceManager.GetObject("CellIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestCasinoIcon {
            get {
                object obj = ResourceManager.GetObject("ChestCasinoIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestDamageIcon {
            get {
                object obj = ResourceManager.GetObject("ChestDamageIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestEquipIcon {
            get {
                object obj = ResourceManager.GetObject("ChestEquipIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestHealIcon {
            get {
                object obj = ResourceManager.GetObject("ChestHealIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestInvisibleIcon {
            get {
                object obj = ResourceManager.GetObject("ChestInvisibleIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestLargeDamageIcon {
            get {
                object obj = ResourceManager.GetObject("ChestLargeDamageIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestLargeHealIcon {
            get {
                object obj = ResourceManager.GetObject("ChestLargeHealIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestLargeIcon {
            get {
                object obj = ResourceManager.GetObject("ChestLargeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestLargeUtilIcon {
            get {
                object obj = ResourceManager.GetObject("ChestLargeUtilIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestLegendaryIcon {
            get {
                object obj = ResourceManager.GetObject("ChestLegendaryIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestLunarIcon {
            get {
                object obj = ResourceManager.GetObject("ChestLunarIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestTimedIcon {
            get {
                object obj = ResourceManager.GetObject("ChestTimedIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestUtilIcon {
            get {
                object obj = ResourceManager.GetObject("ChestUtilIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestVoid {
            get {
                object obj = ResourceManager.GetObject("ChestVoid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChestVoidPotential {
            get {
                object obj = ResourceManager.GetObject("ChestVoidPotential", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CleanseIcon {
            get {
                object obj = ResourceManager.GetObject("CleanseIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneEmergencyIcon {
            get {
                object obj = ResourceManager.GetObject("DroneEmergencyIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneEquipmentIcon {
            get {
                object obj = ResourceManager.GetObject("DroneEquipmentIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneFlameIcon {
            get {
                object obj = ResourceManager.GetObject("DroneFlameIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneHealIcon {
            get {
                object obj = ResourceManager.GetObject("DroneHealIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneMegaIcon {
            get {
                object obj = ResourceManager.GetObject("DroneMegaIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneMissileIcon {
            get {
                object obj = ResourceManager.GetObject("DroneMissileIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DroneTurretIcon {
            get {
                object obj = ResourceManager.GetObject("DroneTurretIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExclamationIcon {
            get {
                object obj = ResourceManager.GetObject("ExclamationIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LockedIcon {
            get {
                object obj = ResourceManager.GetObject("LockedIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LockedIconAlt {
            get {
                object obj = ResourceManager.GetObject("LockedIconAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oldduplicatorbundle {
            get {
                object obj = ResourceManager.GetObject("oldduplicatorbundle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixBlueIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixBlueIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixGreenIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixGreenIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixHauntedIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixHauntedIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixLunarIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixLunarIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixPoisonIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixPoisonIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixRedIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixRedIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexAffixWhiteIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexAffixWhiteIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexEffigyIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexEffigyIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexMeteorIcon {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexMeteorIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexPotionIconChanged {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexPotionIconChanged", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OutlineChangedtexTonicIcontonic {
            get {
                object obj = ResourceManager.GetObject("OutlineChangedtexTonicIcontonic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PingIconShippingDrone {
            get {
                object obj = ResourceManager.GetObject("PingIconShippingDrone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PingIconVoidEradicator {
            get {
                object obj = ResourceManager.GetObject("PingIconVoidEradicator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PingLemurianEgg {
            get {
                object obj = ResourceManager.GetObject("PingLemurianEgg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pingShrineShaping {
            get {
                object obj = ResourceManager.GetObject("pingShrineShaping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PortalIcon {
            get {
                object obj = ResourceManager.GetObject("PortalIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrimordialTeleporterChargedIcon {
            get {
                object obj = ResourceManager.GetObject("PrimordialTeleporterChargedIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrimordialTeleporterIcon {
            get {
                object obj = ResourceManager.GetObject("PrimordialTeleporterIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrinterIcon {
            get {
                object obj = ResourceManager.GetObject("PrinterIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrinterLargeIcon {
            get {
                object obj = ResourceManager.GetObject("PrinterLargeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrinterMiliIcon {
            get {
                object obj = ResourceManager.GetObject("PrinterMiliIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrinterSuperLarge {
            get {
                object obj = ResourceManager.GetObject("PrinterSuperLarge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PrinterWildIcon {
            get {
                object obj = ResourceManager.GetObject("PrinterWildIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ScavBagIcon {
            get {
                object obj = ResourceManager.GetObject("ScavBagIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ScrapperIcon {
            get {
                object obj = ResourceManager.GetObject("ScrapperIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SeerIcon {
            get {
                object obj = ResourceManager.GetObject("SeerIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ShrineBloodIcon {
            get {
                object obj = ResourceManager.GetObject("ShrineBloodIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ShrineChanceIcon {
            get {
                object obj = ResourceManager.GetObject("ShrineChanceIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ShrineGoldIcon {
            get {
                object obj = ResourceManager.GetObject("ShrineGoldIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ShrineHealIcon {
            get {
                object obj = ResourceManager.GetObject("ShrineHealIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ShrineMountainIcon {
            get {
                object obj = ResourceManager.GetObject("ShrineMountainIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ShrineOrderIcon {
            get {
                object obj = ResourceManager.GetObject("ShrineOrderIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpStShrineAegis {
            get {
                object obj = ResourceManager.GetObject("SpStShrineAegis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpStShrineCloaked {
            get {
                object obj = ResourceManager.GetObject("SpStShrineCloaked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SS2_DroneDuplicate {
            get {
                object obj = ResourceManager.GetObject("SS2_DroneDuplicate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SS2_DroneScrapper {
            get {
                object obj = ResourceManager.GetObject("SS2_DroneScrapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SS2_DroneShock {
            get {
                object obj = ResourceManager.GetObject("SS2_DroneShock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texAffixAurelioniteIcon {
            get {
                object obj = ResourceManager.GetObject("texAffixAurelioniteIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texAffixBeadIcon {
            get {
                object obj = ResourceManager.GetObject("texAffixBeadIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texAffixCloakIcon {
            get {
                object obj = ResourceManager.GetObject("texAffixCloakIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texAffixGravityIcon {
            get {
                object obj = ResourceManager.GetObject("texAffixGravityIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texAffixPlatedIcon {
            get {
                object obj = ResourceManager.GetObject("texAffixPlatedIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texAffixRaging {
            get {
                object obj = ResourceManager.GetObject("texAffixRaging", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyBrother {
            get {
                object obj = ResourceManager.GetObject("texBodyBrother", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyBrotherHurt {
            get {
                object obj = ResourceManager.GetObject("texBodyBrotherHurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyClayMan {
            get {
                object obj = ResourceManager.GetObject("texBodyClayMan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyDevotedElder {
            get {
                object obj = ResourceManager.GetObject("texBodyDevotedElder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyDevotedLemurian {
            get {
                object obj = ResourceManager.GetObject("texBodyDevotedLemurian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyEngiWalkerTurret {
            get {
                object obj = ResourceManager.GetObject("texBodyEngiWalkerTurret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyRoboBallBuddyGreen {
            get {
                object obj = ResourceManager.GetObject("texBodyRoboBallBuddyGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyRoboBallBuddyRed {
            get {
                object obj = ResourceManager.GetObject("texBodyRoboBallBuddyRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodySquidTurret {
            get {
                object obj = ResourceManager.GetObject("texBodySquidTurret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyTitanGoldAlly {
            get {
                object obj = ResourceManager.GetObject("texBodyTitanGoldAlly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBodyWispSoul {
            get {
                object obj = ResourceManager.GetObject("texBodyWispSoul", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffAffixEcho {
            get {
                object obj = ResourceManager.GetObject("texBuffAffixEcho", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffaffixhaunterrecipiet {
            get {
                object obj = ResourceManager.GetObject("texBuffaffixhaunterrecipiet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffaffixhaunterrecipietmini {
            get {
                object obj = ResourceManager.GetObject("texBuffaffixhaunterrecipietmini", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffBeetleUp {
            get {
                object obj = ResourceManager.GetObject("texBuffBeetleUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffBodyArmor {
            get {
                object obj = ResourceManager.GetObject("texBuffBodyArmor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffBrokenCube {
            get {
                object obj = ResourceManager.GetObject("texBuffBrokenCube", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffEgg {
            get {
                object obj = ResourceManager.GetObject("texBuffEgg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffFeather {
            get {
                object obj = ResourceManager.GetObject("texBuffFeather", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffFrostRelic {
            get {
                object obj = ResourceManager.GetObject("texBuffFrostRelic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffHeadStompOff {
            get {
                object obj = ResourceManager.GetObject("texBuffHeadStompOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffHeadStompOn {
            get {
                object obj = ResourceManager.GetObject("texBuffHeadStompOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffLunarShellIcon {
            get {
                object obj = ResourceManager.GetObject("texBuffLunarShellIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffMercExposeIcon {
            get {
                object obj = ResourceManager.GetObject("texBuffMercExposeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffRaincoat {
            get {
                object obj = ResourceManager.GetObject("texBuffRaincoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffRoundShieldBuff {
            get {
                object obj = ResourceManager.GetObject("texBuffRoundShieldBuff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffShuriken {
            get {
                object obj = ResourceManager.GetObject("texBuffShuriken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBuffTincture {
            get {
                object obj = ResourceManager.GetObject("texBuffTincture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoBlightSkin {
            get {
                object obj = ResourceManager.GetObject("texCrocoBlightSkin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoDiffuseBlight {
            get {
                object obj = ResourceManager.GetObject("texCrocoDiffuseBlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoEmissionAlt {
            get {
                object obj = ResourceManager.GetObject("texCrocoEmissionAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoEmissionBlight {
            get {
                object obj = ResourceManager.GetObject("texCrocoEmissionBlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoPoisonMask___Copy {
            get {
                object obj = ResourceManager.GetObject("texCrocoPoisonMask___Copy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoPoisonMaskBlight {
            get {
                object obj = ResourceManager.GetObject("texCrocoPoisonMaskBlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoSkinFlow {
            get {
                object obj = ResourceManager.GetObject("texCrocoSkinFlow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiTurretAltColossusDiffuse {
            get {
                object obj = ResourceManager.GetObject("texEngiTurretAltColossusDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiTurretDiffuseAlt {
            get {
                object obj = ResourceManager.GetObject("texEngiTurretDiffuseAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEquipmentBossBG {
            get {
                object obj = ResourceManager.GetObject("texEquipmentBossBG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEquipmentLunarBG {
            get {
                object obj = ResourceManager.GetObject("texEquipmentLunarBG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texItemNullEquip {
            get {
                object obj = ResourceManager.GetObject("texItemNullEquip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texItemUsedKey {
            get {
                object obj = ResourceManager.GetObject("texItemUsedKey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texItemUsedKeyVoid {
            get {
                object obj = ResourceManager.GetObject("texItemUsedKeyVoid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texItemUsedPrayer {
            get {
                object obj = ResourceManager.GetObject("texItemUsedPrayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texLunarPortalOnUseIcon {
            get {
                object obj = ResourceManager.GetObject("texLunarPortalOnUseIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercOniBlues {
            get {
                object obj = ResourceManager.GetObject("texMercOniBlues", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texOniMercSwordDiffuse {
            get {
                object obj = ResourceManager.GetObject("texOniMercSwordDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampBeetleBreathBlight {
            get {
                object obj = ResourceManager.GetObject("texRampBeetleBreathBlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseBlight {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseBlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseBlightAlt {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseBlightAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseDarkDark {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseDarkDark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseDarkDarkAlt {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseDarkDarkAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseDarkLessDark {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseDarkLessDark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampEngiAlt {
            get {
                object obj = ResourceManager.GetObject("texRampEngiAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampFallbootsGreen {
            get {
                object obj = ResourceManager.GetObject("texRampFallbootsGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampFallbootsRed {
            get {
                object obj = ResourceManager.GetObject("texRampFallbootsRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntress {
            get {
                object obj = ResourceManager.GetObject("texRampHuntress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressGreen {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressRed {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoft {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoftGreen {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoftGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoftRed {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoftRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampMercDustGreen {
            get {
                object obj = ResourceManager.GetObject("texRampMercDustGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampMercDustRed {
            get {
                object obj = ResourceManager.GetObject("texRampMercDustRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotVineForColossus {
            get {
                object obj = ResourceManager.GetObject("texTreebotVineForColossus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UniqueAffixVoid {
            get {
                object obj = ResourceManager.GetObject("UniqueAffixVoid", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
